{"uuid":"aa8c1433-6bd4-4784-8dcf-86bb1fa88380","historyId":"4e8d1713bcf936d44add5d1126c55b86","testCaseId":"[engine:junit-jupiter]/[class:tests.ContactRemovalTests]/[method:canRemoveAllContactsAtOnce()]","testCaseName":"canRemoveAllContactsAtOnce()","fullName":"tests.ContactRemovalTests.canRemoveAllContactsAtOnce","labels":[{"name":"junit.platform.uniqueid","value":"[engine:junit-jupiter]/[class:tests.ContactRemovalTests]/[method:canRemoveAllContactsAtOnce()]"},{"name":"host","value":"kristina-MS-7924"},{"name":"thread","value":"19200@kristina-MS-7924.Test worker(1)"},{"name":"framework","value":"junit-platform"},{"name":"language","value":"java"},{"name":"package","value":"tests.ContactRemovalTests"},{"name":"testClass","value":"tests.ContactRemovalTests"},{"name":"testMethod","value":"canRemoveAllContactsAtOnce"},{"name":"suite","value":"tests.ContactRemovalTests"}],"links":[],"name":"canRemoveAllContactsAtOnce()","status":"broken","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment] due to: Error calling DriverManager#getConnection [null]","trace":"org.hibernate.service.spi.ServiceException: Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment] due to: Error calling DriverManager#getConnection [null]\n\tat org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:276)\n\tat org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:238)\n\tat org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:215)\n\tat org.hibernate.boot.model.relational.Database.<init>(Database.java:45)\n\tat org.hibernate.boot.internal.InFlightMetadataCollectorImpl.getDatabase(InFlightMetadataCollectorImpl.java:230)\n\tat org.hibernate.boot.internal.InFlightMetadataCollectorImpl.<init>(InFlightMetadataCollectorImpl.java:198)\n\tat org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:166)\n\tat org.hibernate.boot.model.process.spi.MetadataBuildingProcess.build(MetadataBuildingProcess.java:125)\n\tat org.hibernate.boot.internal.MetadataBuilderImpl.build(MetadataBuilderImpl.java:451)\n\tat org.hibernate.boot.internal.MetadataBuilderImpl.build(MetadataBuilderImpl.java:102)\n\tat org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:910)\n\tat org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:960)\n\tat manager.HibernateHelper.<init>(HibernateHelper.java:32)\n\tat manager.ApplicationManager.hbm(ApplicationManager.java:99)\n\tat tests.ContactRemovalTests.canRemoveAllContactsAtOnce(ContactRemovalTests.java:36)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:567)\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1511)\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1511)\n\tSuppressed: java.lang.RuntimeException: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure\n\nThe last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.\n\t\tat manager.JdbcHelper.checkConsistency(JdbcHelper.java:45)\n\t\tat tests.TestBase.checkDatabaseConsistency(TestBase.java:37)\n\t\t... 3 more\n\tCaused by: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure\n\nThe last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.\n\t\tat com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:165)\n\t\tat com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:55)\n\t\tat com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:833)\n\t\tat com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:416)\n\t\tat com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:238)\n\t\tat com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:180)\n\t\tat java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)\n\t\tat java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)\n\t\tat manager.JdbcHelper.checkConsistency(JdbcHelper.java:38)\n\t\t... 4 more\n\tCaused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure\n\nThe last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.\n\t\tat java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)\n\t\tat java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)\n\t\tat com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:52)\n\t\tat com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:95)\n\t\tat com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:140)\n\t\tat com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:156)\n\t\tat com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:79)\n\t\tat com.mysql.cj.NativeSession.connect(NativeSession.java:142)\n\t\tat com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:957)\n\t\tat com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:821)\n\t\t... 10 more\n\tCaused by: java.net.ConnectException: В соединении отказано\n\t\tat java.base/sun.nio.ch.Net.connect0(Native Method)\n\t\tat java.base/sun.nio.ch.Net.connect(Net.java:576)\n\t\tat java.base/sun.nio.ch.Net.connect(Net.java:565)\n\t\tat java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)\n\t\tat java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333)\n\t\tat java.base/java.net.Socket.connect(Socket.java:645)\n\t\tat com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:144)\n\t\tat com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:53)\n\t\t... 13 more\nCaused by: org.hibernate.exception.JDBCConnectionException: Error calling DriverManager#getConnection [null]\n\tat org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:100)\n\tat org.hibernate.engine.jdbc.connections.internal.BasicConnectionCreator$1.convert(BasicConnectionCreator.java:107)\n\tat org.hibernate.engine.jdbc.connections.internal.BasicConnectionCreator.convertSqlException(BasicConnectionCreator.java:132)\n\tat org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionCreator.makeConnection(DriverManagerConnectionCreator.java:39)\n\tat org.hibernate.engine.jdbc.connections.internal.BasicConnectionCreator.createConnection(BasicConnectionCreator.java:61)\n\tat org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl$PooledConnections.addConnections(DriverManagerConnectionProviderImpl.java:497)\n\tat org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl$PooledConnections.<init>(DriverManagerConnectionProviderImpl.java:363)\n\tat org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl$PooledConnections$Builder.build(DriverManagerConnectionProviderImpl.java:548)\n\tat org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl.buildPool(DriverManagerConnectionProviderImpl.java:101)\n\tat org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl.configure(DriverManagerConnectionProviderImpl.java:81)\n\tat org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.configureService(StandardServiceRegistryImpl.java:135)\n\tat org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:247)\n\tat org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:215)\n\tat org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.buildJdbcConnectionAccess(JdbcEnvironmentInitiator.java:354)\n\tat org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.getJdbcEnvironmentUsingJdbcMetadata(JdbcEnvironmentInitiator.java:236)\n\tat org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:82)\n\tat org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:43)\n\tat org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.initiateService(StandardServiceRegistryImpl.java:129)\n\tat org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:263)\n\t... 17 more\nCaused by: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure\n\nThe last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.\n\tat com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:165)\n\tat com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:55)\n\tat com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:833)\n\tat com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:416)\n\tat com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:238)\n\tat com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:180)\n\tat java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)\n\tat java.sql/java.sql.DriverManager.getConnection(DriverManager.java:189)\n\tat org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionCreator.makeConnection(DriverManagerConnectionCreator.java:36)\n\t... 32 more\nCaused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure\n\nThe last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.\n\tat jdk.internal.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)\n\tat java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)\n\tat java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)\n\tat java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)\n\tat com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:52)\n\tat com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:95)\n\tat com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:140)\n\tat com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:156)\n\tat com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:79)\n\tat com.mysql.cj.NativeSession.connect(NativeSession.java:142)\n\tat com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:957)\n\tat com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:821)\n\t... 38 more\nCaused by: java.net.ConnectException: В соединении отказано\n\tat java.base/sun.nio.ch.Net.connect0(Native Method)\n\tat java.base/sun.nio.ch.Net.connect(Net.java:576)\n\tat java.base/sun.nio.ch.Net.connect(Net.java:565)\n\tat java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)\n\tat java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333)\n\tat java.base/java.net.Socket.connect(Socket.java:645)\n\tat com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:144)\n\tat com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:53)\n\t... 41 more\n"},"stage":"finished","description":"","steps":[],"attachments":[],"parameters":[],"start":1748154999353,"stop":1748154999370}