{"uuid":"d3640366-773b-4b96-a452-8f6f9d25ae2a","historyId":"ee9fc4d016267ac959617b5a92a87c04","testCaseId":"[engine:junit-jupiter]/[class:tests.ContactCreationTests]/[method:canCreateContactWithPhoto()]","testCaseName":"canCreateContactWithPhoto()","fullName":"tests.ContactCreationTests.canCreateContactWithPhoto","labels":[{"name":"junit.platform.uniqueid","value":"[engine:junit-jupiter]/[class:tests.ContactCreationTests]/[method:canCreateContactWithPhoto()]"},{"name":"host","value":"kristina-MS-7924"},{"name":"thread","value":"19200@kristina-MS-7924.Test worker(1)"},{"name":"framework","value":"junit-platform"},{"name":"language","value":"java"},{"name":"package","value":"tests.ContactCreationTests"},{"name":"testClass","value":"tests.ContactCreationTests"},{"name":"testMethod","value":"canCreateContactWithPhoto"},{"name":"suite","value":"tests.ContactCreationTests"}],"links":[],"name":"canCreateContactWithPhoto()","status":"broken","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"Reached error page: about:neterror?e=connectionFailure&u=http%3A//localhost/addressbook/index.php&c=UTF-8&d=Firefox%20can%E2%80%99t%20establish%20a%20connection%20to%20the%20server%20at%20localhost.\nBuild info: version: '4.30.0', revision: '509c7f17cc*'\nSystem info: os.name: 'Linux', os.arch: 'amd64', os.version: '6.8.0-59-generic', java.version: '16.0.2'\nDriver info: org.openqa.selenium.firefox.FirefoxDriver\nCommand: [d19a013b-1695-4ecf-8d95-a4bd0e962dbf, get {url=http://localhost/addressbook/index.php}]\nCapabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 138.0.4, moz:accessibilityChecks: false, moz:buildID: 20250517143237, moz:geckodriverVersion: 0.36.0, moz:headless: false, moz:platformVersion: 6.8.0-59-generic, moz:processID: 19335, moz:profile: /tmp/rust_mozprofile20gpFt, moz:shutdownTimeout: 60000, moz:webdriverClick: true, moz:windowless: false, pageLoadStrategy: normal, platformName: linux, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, userAgent: Mozilla/5.0 (X11; Linux x86...}\nSession ID: d19a013b-1695-4ecf-8d95-a4bd0e962dbf","trace":"org.openqa.selenium.WebDriverException: Reached error page: about:neterror?e=connectionFailure&u=http%3A//localhost/addressbook/index.php&c=UTF-8&d=Firefox%20can%E2%80%99t%20establish%20a%20connection%20to%20the%20server%20at%20localhost.\nBuild info: version: '4.30.0', revision: '509c7f17cc*'\nSystem info: os.name: 'Linux', os.arch: 'amd64', os.version: '6.8.0-59-generic', java.version: '16.0.2'\nDriver info: org.openqa.selenium.firefox.FirefoxDriver\nCommand: [d19a013b-1695-4ecf-8d95-a4bd0e962dbf, get {url=http://localhost/addressbook/index.php}]\nCapabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 138.0.4, moz:accessibilityChecks: false, moz:buildID: 20250517143237, moz:geckodriverVersion: 0.36.0, moz:headless: false, moz:platformVersion: 6.8.0-59-generic, moz:processID: 19335, moz:profile: /tmp/rust_mozprofile20gpFt, moz:shutdownTimeout: 60000, moz:webdriverClick: true, moz:windowless: false, pageLoadStrategy: normal, platformName: linux, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, userAgent: Mozilla/5.0 (X11; Linux x86...}\nSession ID: d19a013b-1695-4ecf-8d95-a4bd0e962dbf\n\tat java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)\n\tat java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)\n\tat org.openqa.selenium.remote.ErrorCodec.decode(ErrorCodec.java:167)\n\tat org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:138)\n\tat org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:50)\n\tat org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:215)\n\tat org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:216)\n\tat org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:174)\n\tat org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:545)\n\tat org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:313)\n\tat manager.ApplicationManager.init(ApplicationManager.java:54)\n\tat tests.TestBase.setUp(TestBase.java:30)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:567)\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1511)\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1511)\n\tSuppressed: java.lang.RuntimeException: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure\n\nThe last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.\n\t\tat manager.JdbcHelper.checkConsistency(JdbcHelper.java:45)\n\t\tat tests.TestBase.checkDatabaseConsistency(TestBase.java:37)\n\t\t... 3 more\n\tCaused by: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure\n\nThe last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.\n\t\tat com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:165)\n\t\tat com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:55)\n\t\tat com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:833)\n\t\tat com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:416)\n\t\tat com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:238)\n\t\tat com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:180)\n\t\tat java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)\n\t\tat java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)\n\t\tat manager.JdbcHelper.checkConsistency(JdbcHelper.java:38)\n\t\t... 4 more\n\tCaused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure\n\nThe last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.\n\t\tat java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)\n\t\tat java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)\n\t\tat com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:52)\n\t\tat com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:95)\n\t\tat com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:140)\n\t\tat com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:156)\n\t\tat com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:79)\n\t\tat com.mysql.cj.NativeSession.connect(NativeSession.java:142)\n\t\tat com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:957)\n\t\tat com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:821)\n\t\t... 10 more\n\tCaused by: java.net.ConnectException: В соединении отказано\n\t\tat java.base/sun.nio.ch.Net.connect0(Native Method)\n\t\tat java.base/sun.nio.ch.Net.connect(Net.java:576)\n\t\tat java.base/sun.nio.ch.Net.connect(Net.java:565)\n\t\tat java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)\n\t\tat java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333)\n\t\tat java.base/java.net.Socket.connect(Socket.java:645)\n\t\tat com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:144)\n\t\tat com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:53)\n\t\t... 13 more\n"},"stage":"finished","description":"","steps":[],"attachments":[],"parameters":[],"start":1748154982372,"stop":1748154997935}